/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    'Dashboard': RouteRecordInfo<'Dashboard', '/', Record<never, never>, Record<never, never>>,
    '$error': RouteRecordInfo<'$error', '/:error(.*)', { error: ParamValue<true> }, { error: ParamValue<false> }>,
    'Addresses': RouteRecordInfo<'Addresses', '/addresses', Record<never, never>, Record<never, never>>,
    'AuthGoogleCallback': RouteRecordInfo<'AuthGoogleCallback', '/auth/google/callback', Record<never, never>, Record<never, never>>,
    'ColorsList': RouteRecordInfo<'ColorsList', '/colors-list', Record<never, never>, Record<never, never>>,
    'Demo': RouteRecordInfo<'Demo', '/demo', Record<never, never>, Record<never, never>>,
    'ExtendedDemo': RouteRecordInfo<'ExtendedDemo', '/demo/extended', Record<never, never>, Record<never, never>>,
    'Developers': RouteRecordInfo<'Developers', '/developers', Record<never, never>, Record<never, never>>,
    'Files': RouteRecordInfo<'Files', '/files', Record<never, never>, Record<never, never>>,
    'ForgotPassword': RouteRecordInfo<'ForgotPassword', '/forgot-password', Record<never, never>, Record<never, never>>,
    'login': RouteRecordInfo<'login', '/login', Record<never, never>, Record<never, never>>,
    'Map': RouteRecordInfo<'Map', '/map', Record<never, never>, Record<never, never>>,
    'MyProfile': RouteRecordInfo<'MyProfile', '/my-profile', Record<never, never>, Record<never, never>>,
    'MyShifts': RouteRecordInfo<'MyShifts', '/my-shifts', Record<never, never>, Record<never, never>>,
    'password-reset$token': RouteRecordInfo<'password-reset$token', '/password-reset/:token(.*)', { token: ParamValue<true> }, { token: ParamValue<false> }>,
    'privacy-policy': RouteRecordInfo<'privacy-policy', '/privacy-policy', Record<never, never>, Record<never, never>>,
    'PromptTemplates': RouteRecordInfo<'PromptTemplates', '/prompt-templates', Record<never, never>, Record<never, never>>,
    'refund-policy': RouteRecordInfo<'refund-policy', '/refund-policy', Record<never, never>, Record<never, never>>,
    'register': RouteRecordInfo<'register', '/register', Record<never, never>, Record<never, never>>,
    'Repositories': RouteRecordInfo<'Repositories', '/repositories', Record<never, never>, Record<never, never>>,
    'StaffRoster': RouteRecordInfo<'StaffRoster', '/roster', Record<never, never>, Record<never, never>>,
    'Settings': RouteRecordInfo<'Settings', '/settings', Record<never, never>, Record<never, never>>,
    'ShiftLog': RouteRecordInfo<'ShiftLog', '/shift-log', Record<never, never>, Record<never, never>>,
    'terms-of-service': RouteRecordInfo<'terms-of-service', '/terms-of-service', Record<never, never>, Record<never, never>>,
    'Triggers': RouteRecordInfo<'Triggers', '/triggers', Record<never, never>, Record<never, never>>,
  }
}
