INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('USD', 'US Dollar', '$', '$', 2, 0, 'US dollars');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('EUR', 'Euro', '€', '€', 2, 0, 'Euros');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('JPY', 'Japanese Yen', '¥', '￥', 0, 0, 'Japanese yen');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('GBP', 'British Pound', '£', '£', 2, 0, 'British pounds');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('AUD', 'Australian Dollar', 'A$', '$', 2, 0, 'Australian dollars');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('CAD', 'Canadian Dollar', 'CA$', '$', 2, 0, 'Canadian dollars');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('CHF', 'Swiss Franc', 'CHF', 'CHF', 2, 0, 'Swiss francs');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('CNY', 'Chinese Yuan', 'CN¥', '¥', 2, 0, 'Chinese yuan');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('SEK', 'Swedish Krona', 'SEK', 'kr', 2, 0, 'Swedish kronor');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('NZD', 'New Zealand Dollar', 'NZ$', '$', 2, 0, 'New Zealand dollars');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('MXN', 'Mexican Peso', 'MX$', '$', 2, 0, 'Mexican pesos');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('SGD', 'Singapore Dollar', 'SGD', '$', 2, 0, 'Singapore dollars');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('HKD', 'Hong Kong Dollar', 'HK$', '$', 2, 0, 'Hong Kong dollars');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('NOK', 'Norwegian Krone', 'NOK', 'kr', 2, 0, 'Norwegian kroner');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('KRW', 'South Korean Won', '₩', '₩', 0, 0, 'South Korean won');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('TRY', 'Turkish Lira', '₺', '₺', 2, 0, 'Turkish liras');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('RUB', 'Russian Ruble', 'RUB', '₽', 2, 0, 'Russian rubles');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('INR', 'Indian Rupee', '₹', '₹', 2, 0, 'Indian rupees');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('BRL', 'Brazilian Real', 'R$', 'R$', 2, 0, 'Brazilian reals');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('ZAR', 'South African Rand', 'ZAR', 'R', 2, 0, 'South African rand');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('PLN', 'Polish Zloty', 'zł', 'zł', 2, 0, 'Polish zlotys');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('PHP', 'Philippine Peso', '₱', '₱', 2, 0, 'Philippine pesos');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('AED', 'United Arab Emirates Dirham', 'AED', 'د.إ.‏', 2, 0, 'UAE dirhams');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('THB', 'Thai Baht', '฿', '฿', 2, 0, 'Thai baht');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('IDR', 'Indonesian Rupiah', 'IDR', 'Rp', 0, 0, 'Indonesian rupiahs');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('MYR', 'Malaysian Ringgit', 'MYR', 'RM', 2, 0, 'Malaysian ringgits');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('SAR', 'Saudi Riyal', 'SAR', 'ر.س.‏', 2, 0, 'Saudi riyals');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('CZK', 'Czech Koruna', 'CZK', 'Kč', 2, 0, 'Czech korunas');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('DKK', 'Danish Krone', 'DKK', 'kr', 2, 0, 'Danish kroner');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('ARS', 'Argentine Peso', 'ARS', '$', 2, 0, 'Argentine pesos');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('CLP', 'Chilean Peso', 'CLP', '$', 0, 0, 'Chilean pesos');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('COP', 'Colombian Peso', 'COP', '$', 0, 0, 'Colombian pesos');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('EGP', 'Egyptian Pound', 'EGP', 'ج.م.‏', 2, 0, 'Egyptian pounds');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('NGN', 'Nigerian Naira', 'NGN', '₦', 2, 0, 'Nigerian nairas');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('PKR', 'Pakistani Rupee', 'PKR', '₨', 2, 0, 'Pakistani rupees');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('BDT', 'Bangladeshi Taka', 'BDT', '৳', 2, 0, 'Bangladeshi takas');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('VND', 'Vietnamese Dong', '₫', '₫', 0, 0, 'Vietnamese dong');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('UAH', 'Ukrainian Hryvnia', 'UAH', '₴', 2, 0, 'Ukrainian hryvnias');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('QAR', 'Qatari Rial', 'QAR', 'ر.ق.‏', 2, 0, 'Qatari rials');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('KWD', 'Kuwaiti Dinar', 'KWD', 'د.ك.‏', 3, 0, 'Kuwaiti dinars');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('BHD', 'Bahraini Dinar', 'BHD', 'د.ب.‏', 3, 0, 'Bahraini dinars');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('OMR', 'Omani Rial', 'OMR', 'ر.ع.‏', 3, 0, 'Omani rials');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('JOD', 'Jordanian Dinar', 'JOD', 'د.ا.‏', 3, 0, 'Jordanian dinars');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('IQD', 'Iraqi Dinar', 'IQD', 'ع.د.‏', 0, 0, 'Iraqi dinars');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('LKR', 'Sri Lankan Rupee', 'LKR', 'රු', 2, 0, 'Sri Lankan rupees');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('KES', 'Kenyan Shilling', 'KES', 'KSh', 2, 0, 'Kenyan shillings');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('TZS', 'Tanzanian Shilling', 'TZS', 'TSh', 0, 0, 'Tanzanian shillings');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('UGX', 'Ugandan Shilling', 'UGX', 'USh', 0, 0, 'Ugandan shillings');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('MAD', 'Moroccan Dirham', 'MAD', 'د.م.‏', 2, 0, 'Moroccan dirhams');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('DZD', 'Algerian Dinar', 'DZD', 'د.ج.‏', 2, 0, 'Algerian dinars');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('TND', 'Tunisian Dinar', 'TND', 'د.ت.‏', 3, 0, 'Tunisian dinars');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('GHS', 'Ghanaian Cedi', 'GHS', '₵', 2, 0, 'Ghanaian cedis');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('ETB', 'Ethiopian Birr', 'ETB', 'ብር', 2, 0, 'Ethiopian birrs');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('RWF', 'Rwandan Franc', 'RWF', 'FRw', 0, 0, 'Rwandan francs');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('XAF', 'Central African CFA Franc', 'FCFA', 'FCFA', 0, 0, 'Central African CFA francs');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('XOF', 'West African CFA Franc', 'CFA', 'CFA', 0, 0, 'West African CFA francs');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('CDF', 'Congolese Franc', 'CDF', 'FC', 2, 0, 'Congolese francs');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('ZMW', 'Zambian Kwacha', 'ZMW', 'ZK', 2, 0, 'Zambian kwachas');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('MZN', 'Mozambican Metical', 'MZN', 'MTn', 2, 0, 'Mozambican meticals');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('AFN', 'Afghan Afghani', 'AFN', '؋', 2, 0, 'Afghan Afghanis');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('ALL', 'Albanian Lek', 'ALL', 'Lek', 2, 0, 'Albanian lekë');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('AMD', 'Armenian Dram', 'AMD', '֏', 2, 0, 'Armenian drams');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('AZN', 'Azerbaijani Manat', 'AZN', '₼', 2, 0, 'Azerbaijani manats');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('BAM', 'Bosnia-Herzegovina Convertible Mark', 'BAM', 'KM', 2, 0, 'Bosnia-Herzegovina convertible marks');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('BBD', 'Barbadian Dollar', 'BBD', '$', 2, 0, 'Barbadian dollars');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('BIF', 'Burundian Franc', 'BIF', 'FBu', 0, 0, 'Burundian francs');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('BND', 'Brunei Dollar', 'BND', '$', 2, 0, 'Brunei dollars');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('BTN', 'Bhutanese Ngultrum', 'BTN', 'Nu.', 2, 0, 'Bhutanese ngultrums');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('BYN', 'Belarusian Ruble', 'BYN', 'Br', 2, 0, 'Belarusian rubles');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('DJF', 'Djiboutian Franc', 'DJF', 'Fdj', 0, 0, 'Djiboutian francs');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('DOP', 'Dominican Peso', 'DOP', 'RD$', 2, 0, 'Dominican pesos');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('FJD', 'Fijian Dollar', 'FJD', '$', 2, 0, 'Fijian dollars');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('GEL', 'Georgian Lari', 'GEL', '₾', 2, 0, 'Georgian lari');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('GTQ', 'Guatemalan Quetzal', 'GTQ', 'Q', 2, 0, 'Guatemalan quetzals');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('HNL', 'Honduran Lempira', 'HNL', 'L', 2, 0, 'Honduran lempiras');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('HRK', 'Croatian Kuna', 'HRK', 'kn', 2, 0, 'Croatian kunas');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('ISK', 'Icelandic Króna', 'ISK', 'kr', 0, 0, 'Icelandic krónur');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('JMD', 'Jamaican Dollar', 'JMD', 'J$', 2, 0, 'Jamaican dollars');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('KGS', 'Kyrgyzstani Som', 'KGS', 'сом', 2, 0, 'Kyrgyzstani soms');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('KHR', 'Cambodian Riel', 'KHR', '៛', 2, 0, 'Cambodian riels');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('KMF', 'Comorian Franc', 'KMF', 'CF', 0, 0, 'Comorian francs');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('LAK', 'Lao Kip', 'LAK', '₭', 0, 0, 'Lao kips');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('LSL', 'Lesotho Loti', 'LSL', 'L', 2, 0, 'Lesotho lotis');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('LRD', 'Liberian Dollar', 'LRD', '$', 2, 0, 'Liberian dollars');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('MKD', 'Macedonian Denar', 'MKD', 'ден', 2, 0, 'Macedonian denari');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('MGA', 'Malagasy Ariary', 'MGA', 'Ar', 2, 0, 'Malagasy ariaries');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('MMK', 'Myanmar Kyat', 'MMK', 'K', 0, 0, 'Myanmar kyats');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('MNT', 'Mongolian Tugrik', 'MNT', '₮', 2, 0, 'Mongolian tugriks');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('NAD', 'Namibian Dollar', 'NAD', '$', 2, 0, 'Namibian dollars');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('PAB', 'Panamanian Balboa', 'PAB', 'B/.', 2, 0, 'Panamanian balboas');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('SBD', 'Solomon Islands Dollar', 'SBD', '$', 2, 0, 'Solomon Islands dollars');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('SCR', 'Seychellois Rupee', 'SCR', '₨', 2, 0, 'Seychellois rupees');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('SOS', 'Somali Shilling', 'SOS', 'S', 2, 0, 'Somali shillings');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('TOP', 'Tongan Paʻanga', 'TOP', 'T$', 2, 0, 'Tongan paʻanga');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('UZS', 'Uzbekistani Som', 'UZS', 'сум', 2, 0, 'Uzbekistani soms');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('WST', 'Samoan Tala', 'WST', 'T', 2, 0, 'Samoan tala');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('MRU', 'Mauritanian Ouguiya', 'UM', 'UM', 2, 0, 'Mauritanian ouguiyas');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('BMD', 'Bermudian Dollar', '$', '$', 2, 0, 'Bermudian dollars');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('XCD', 'East Caribbean Dollar', 'EC$', '$', 2, 0, 'East Caribbean dollars');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('VES', 'Venezuelan Bolívar', 'Bs.', 'Bs.', 2, 0, 'Venezuelan bolívares');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('RON', 'Romanian Leu', 'lei', 'lei', 2, 0, 'Romanian lei');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('SLL', 'Sierra Leonean Leone', 'Le', 'Le', 0, 0, 'Sierra Leonean leones');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('BGN', 'Bulgarian Lev', 'лв', 'лв', 2, 0, 'Bulgarian leva');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('GYD', 'Guyanese Dollar', 'G$', '$', 2, 0, 'Guyanese dollars');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('PEN', 'Peruvian Sol', 'S/', 'S/', 2, 0, 'Peruvian soles');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('GMD', 'Gambian Dalasi', 'D', 'D', 2, 0, 'Gambian dalasis');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('SHP', 'Saint Helena Pound', '£', '£', 2, 0, 'Saint Helena pounds');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('UYU', 'Uruguayan Peso', '$U', '$', 2, 0, 'Uruguayan pesos');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('JEP', 'Jersey Pound', '£', '£', 2, 0, 'Jersey pounds');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('TJS', 'Tajikistani Somoni', 'ЅМ', 'ЅМ', 2, 0, 'Tajikistani somonis');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('HTG', 'Haitian Gourde', 'G', 'G', 2, 0, 'Haitian gourdes');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('BZD', 'Belize Dollar', 'BZ$', '$', 2, 0, 'Belize dollars');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('TTD', 'Trinidad and Tobago Dollar', 'TT$', '$', 2, 0, 'Trinidad and Tobago dollars');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('MDL', 'Moldovan Leu', 'L', 'L', 2, 0, 'Moldovan lei');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('KYD', 'Cayman Islands Dollar', '$', '$', 2, 0, 'Cayman Islands dollars');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('CUP', 'Cuban Peso', '₱', '₱', 2, 0, 'Cuban pesos');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('STN', 'São Tomé and Príncipe Dobra', 'Db', 'Db', 2, 0, 'São Tomé and Príncipe dobras');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('CRC', 'Costa Rican Colón', '₡', '₡', 2, 0, 'Costa Rican colóns');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('TVD', 'Tuvaluan Dollar', '$', '$', 2, 0, 'Tuvaluan dollars');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('XDR', 'Special Drawing Rights', 'XDR', 'XDR', 2, 0, 'Special drawing rights');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('LBP', 'Lebanese Pound', 'ل.ل.‏', 'ل.ل.‏', 0, 0, 'Lebanese pounds');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('FOK', 'Faroese Króna', 'kr', 'kr', 2, 0, 'Faroese kronor');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('ZWL', 'Zimbabwean Dollar', '$', '$', 2, 0, 'Zimbabwean dollars');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('KID', 'Kiribati Dollar', '$', '$', 2, 0, 'Kiribati dollars');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('VUV', 'Vanuatu Vatu', 'VT', 'VT', 0, 0, 'Vanuatu vatus');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('FKP', 'Falkland Islands Pound', '£', '£', 2, 0, 'Falkland Islands pounds');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('AWG', 'Aruban Florin', 'ƒ', 'ƒ', 2, 0, 'Aruban florins');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('SLE', 'Sierra Leonean Leone (New)', 'Le', 'Le', 2, 0, 'Sierra Leonean leones');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('PGK', 'Papua New Guinean Kina', 'K', 'K', 2, 0, 'Papua New Guinean kina');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('KZT', 'Kazakhstani Tenge', '₸', '₸', 2, 0, 'Kazakhstani tenges');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('NIO', 'Nicaraguan Córdoba', 'C$', '$', 2, 0, 'Nicaraguan córdobas');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('BWP', 'Botswana Pula', 'P', 'P', 2, 0, 'Botswana pulas');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('PYG', 'Paraguayan Guarani', '₲', '₲', 0, 0, 'Paraguayan guaranies');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('LYD', 'Libyan Dinar', 'ل.د.‏', 'ل.د.‏', 3, 0, 'Libyan dinars');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('MUR', 'Mauritian Rupee', '₨', '₨', 2, 0, 'Mauritian rupees');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('SRD', 'Surinamese Dollar', '$', '$', 2, 0, 'Surinamese dollars');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('SDG', 'Sudanese Pound', 'ج.س.‏', 'ج.س.‏', 2, 0, 'Sudanese pounds');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('GNF', 'Guinean Franc', 'FG', 'FG', 0, 0, 'Guinean francs');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('MOP', 'Macanese Pataca', 'MOP$', '$', 2, 0, 'Macanese patacas');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('CVE', 'Cape Verdean Escudo', 'Esc', 'Esc', 2, 0, 'Cape Verdean escudos');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('GGP', 'Guernsey Pound', '£', '£', 2, 0, 'Guernsey pounds');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('ANG', 'Netherlands Antillean Guilder', 'ƒ', 'ƒ', 2, 0, 'Netherlands Antillean guilders');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('BOB', 'Bolivian Boliviano', 'Bs.', 'Bs.', 2, 0, 'Bolivian bolivianos');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('SSP', 'South Sudanese Pound', '£', '£', 2, 0, 'South Sudanese pounds');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('ERN', 'Eritrean Nakfa', 'Nfk', 'Nfk', 2, 0, 'Eritrean nakfas');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('IRR', 'Iranian Rial', '﷼', '﷼', 0, 0, 'Iranian rials');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('TMT', 'Turkmenistani Manat', 'm', 'm', 2, 0, 'Turkmenistani manats');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('MVR', 'Maldivian Rufiyaa', 'Rf', 'Rf', 2, 0, 'Maldivian rufiyaas');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('IMP', 'Isle of Man Pound', '£', '£', 2, 0, 'Isle of Man pounds');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('YER', 'Yemeni Rial', '﷼', '﷼', 0, 0, 'Yemeni rials');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('AOA', 'Angolan Kwanza', 'Kz', 'Kz', 2, 0, 'Angolan kwanzas');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('TWD', 'New Taiwan Dollar', 'NT$', '$', 2, 0, 'New Taiwan dollars');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('SYP', 'Syrian Pound', '£', '£', 2, 0, 'Syrian pounds');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('XPF', 'CFP Franc', '₣', '₣', 0, 0, 'CFP francs');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('RSD', 'Serbian Dinar', 'дин', 'дин', 2, 0, 'Serbian dinars');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('MWK', 'Malawian Kwacha', 'MK', 'MK', 2, 0, 'Malawian kwachas');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('ILS', 'Israeli New Shekel', '₪', '₪', 2, 0, 'Israeli new shekels');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('HUF', 'Hungarian Forint', 'Ft', 'Ft', 0, 0, 'Hungarian forints');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('SZL', 'Eswatini Lilangeni', 'E', 'E', 2, 0, 'Eswatini emalangeni');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('BSD', 'Bahamian Dollar', 'B$', '$', 2, 0, 'Bahamian dollars');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('NPR', 'Nepalese Rupee', '₨', '₨', 2, 0, 'Nepalese rupees');
INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('GIP', 'Gibraltar Pound', '£', '£', 2, 0, 'Gibraltar pounds');

UPDATE currencies
SET localization = CASE
    WHEN code IN ('USD', 'GBP', 'AUD', 'CAD', 'CHF', 'CNY', 'JPY', 'SGD', 'HKD', 'NZD', 'MXN', 'KRW', 'PHP', 'MYR', 'SAR', 'THB', 'AED', 'INR', 'BRL', 'ZAR', 'SEK', 'DKK', 'NOK', 'TRY') THEN 'before'
    WHEN code IN ('EUR', 'BAM', 'PLN', 'CZK', 'HUF', 'RON', 'BGN') THEN 'after'
    ELSE 'before' -- Default for other currencies if not explicitly mentioned
END;

-- Cryptocurrencies
-- INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('BTC', 'Bitcoin', '₿', '₿', 8, 0, 'Bitcoins');
-- INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('ETH', 'Ethereum', 'Ξ', 'Ξ', 8, 0, 'Ether');
-- INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('USDT', 'Tether', '₮', '₮', 2, 0, 'Tethers');
-- INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('BNB', 'Binance Coin', 'BNB', 'BNB', 8, 0, 'Binance Coins');
-- INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('XRP', 'Ripple', 'XRP', 'XRP', 6, 0, 'Ripples');
-- INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('ADA', 'Cardano', 'ADA', 'ADA', 6, 0, 'Cardanos');
-- INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('SOL', 'Solana', 'SOL', 'SOL', 8, 0, 'Solanas');
-- INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('DOGE', 'Dogecoin', 'Ð', 'Ð', 8, 0, 'Dogecoins');
-- INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('DOT', 'Polkadot', 'DOT', 'DOT', 8, 0, 'Polkadots');
-- INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('MATIC', 'Polygon', 'MATIC', 'MATIC', 8, 0, 'Polygons');
-- INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('AVAX', 'Avalanche', 'AVAX', 'AVAX', 8, 0, 'Avalanches');
-- INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('TRX', 'TRON', 'TRX', 'TRX', 6, 0, 'TRON');
-- INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('SHIB', 'Shiba Inu', 'SHIB', 'SHIB', 0, 0, 'Shiba Inus');
-- INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('LTC', 'Litecoin', 'Ł', 'Ł', 8, 0, 'Litecoins');
-- INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('BCH', 'Bitcoin Cash', 'BCH', 'BCH', 8, 0, 'Bitcoin Cash');
-- INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('XLM', 'Stellar', 'XLM', 'XLM', 8, 0, 'Stellars');
-- INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('ATOM', 'Cosmos', 'ATOM', 'ATOM', 8, 0, 'Atoms');
-- INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('ALGO', 'Algorand', 'ALGO', 'ALGO', 8, 0, 'Algorands');
-- INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('ICP', 'Internet Computer', 'ICP', 'ICP', 8, 0, 'Internet Computers');
-- INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('FTM', 'Fantom', 'FTM', 'FTM', 8, 0, 'Fantoms');
-- INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('DAI', 'Dai', 'DAI', 'DAI', 2, 0, 'Dai');
-- INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('CAKE', 'PancakeSwap', 'CAKE', 'CAKE', 8, 0, 'Cakes');
-- INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('NEAR', 'NEAR Protocol', 'NEAR', 'NEAR', 8, 0, 'NEARs');
-- INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('FIL', 'Filecoin', 'FIL', 'FIL', 8, 0, 'Filecoins');
-- INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('EOS', 'EOS', 'EOS', 'EOS', 8, 0, 'EOS');
-- INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('ZEC', 'Zcash', 'ZEC', 'ZEC', 8, 0, 'Zcash');
-- INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('XTZ', 'Tezos', 'XTZ', 'XTZ', 8, 0, 'Tezoses');
-- INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('QNT', 'Quant', 'QNT', 'QNT', 8, 0, 'Quants');
-- INSERT INTO currencies (code, name, symbol, symbol_native, decimal_digits, rounding, name_plural) VALUES ('HBAR', 'Hedera', 'HBAR', 'HBAR', 8, 0, 'Hederas');
